# Lancer le container batterie

services:
  batterie_sensor:
    build: .
    container_name: batterie_sensor
    command: python -m Couches.Couche1.EndDevices.Batterie
    volumes:
      - ./:/app
    working_dir: /app
  
  gps_sensor:
    build: .
    container_name: gps_sensor
    command: python -m Couches.Couche1.EndDevices.GPSSensor
    volumes:
      - ./:/app
    working_dir: /app

  temperature_sensor:
    build: .
    container_name: temperature_sensor
    command: python -m Couches.Couche1.EndDevices.TemperatureSensor
    volumes:
      - ./:/app
    working_dir: /app

  leader:
    build: .
    container_name: leader
    command: python -m Couches.Couche1.Leader
    volumes:
      - ./:/app
    working_dir: /app
  
  routeur:
    build: .
    container_name: routeur
    command: python -m Couches.Couche1.Routeur
    volumes:
      - ./:/app
    working_dir: /app
  
  mqtt_broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_broker
    ports:
      - "1883:1883"
    
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: zolis_db
    ports:
      - "3306:3306"

  backend:
    build: .
    container_name: backend
    command: python -m Couches.Main
    volumes:
      - ./:/app
    working_dir: /app

  frontend:
    build: .
    container_name: frontend
    command: python -m Couches.WebUI.app
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "5000:5000"

